#!/usr/bin/node

const report = require('./report.js');
const path = require('path');

let dataDir = process.argv[2];
if (!dataDir.endsWith(path.sep)) dataDir += path.sep;
let outDir  = process.argv[3];
if (!outDir.endsWith(path.sep))  outDir  += path.sep;

report(dataDir, outDir);
