#!/usr/bin/node

const analyze_history = require('./lib/analyze_history');



const repo = process.argv[2];
let outDir = process.argv[3] || 'out/';
if (!outDir.endsWith('/')) { outDir += '/' }
const stepWidth = parseInt(process.argv[4] || '250');
const whitelist = process.argv.length >= 5 ? process.argv.slice(5) : undefined;

analyze_history(repo, outDir, stepWidth, whitelist);
