#!/usr/bin/node

"use strict";

const analyze = require('./lib/analyze');



let repo = process.argv[2];
if (!repo.endsWith('/')) { repo += '/' }
const outDir = process.argv[3];
const treeish = process.argv[4];
const whitelist = process.argv.slice(5);

analyze(repo, whitelist, outDir, treeish);
