#!/usr/bin/node

// Creates a CSV of the history of API useage of one module.
// Useage: `./graph_module MODULE USEAGE_JSON...`
// Pass the module to graph and a list of useage json files to extract from

const fs = require('fs');
const Table = require('./lib/Table');
const path = require('path');



const mod = process.argv[2];
let files = process.argv.length == 4 ? process.argv[3] : process.argv.slice(3);
const result = new Table(0);

if (!Array.isArray(files)) {
  files = fs.readdirSync(files).map(filename => { return `${files}${filename}` });
}

for (let file of files) {
  if (!file.toLowerCase().endsWith('.json')) continue;
  const contents = fs.readFileSync(file, { encoding: 'utf-8' });
  const uses = JSON.parse(contents);

  const row = path.basename(file, '.json')
  result.ensureHasRow(row);

  const modStats = uses[mod];
  for (let author in modStats) {
    const usesByAuthor = modStats[author] || 0;
    result.set(row, author, usesByAuthor);
  }
}

console.log(result.toCSV());
