#!/usr/bin/node

// Creates a CSV of the history of API useage of one author.
// Pass the author to extract and a list of useage json files or a dir to extract from

const fs = require('fs');
const Table = require('./lib/Table');
const path = require('path');



const author = process.argv[2];
let files = process.argv.length == 4 ? process.argv[3] : process.argv.slice(3);
const result = new Table(0);

if (!Array.isArray(files)) {
  files = fs.readdirSync(files).map(filename => { return `${files}${filename}` });
}

for (let file of files) {
  if (!file.toLowerCase().endsWith('.json')) continue;
  const contents = fs.readFileSync(file, { encoding: 'utf-8' });
  const uses = JSON.parse(contents);

  for (let mod in uses) {
    const modStats = uses[mod];
    const usesByAuthor = modStats[author] || 0;
    result.set(path.basename(file, '.json'), mod, usesByAuthor);
  }
}

console.log(result.toCSV());
