#!/usr/bin/node

// Creates a CSV of the history of API useage of one author.
// Useage: `./graph_author AUTHOR USEAGE_JSON...`
// Pass the author to extract and a list of useage json files to extract from

const fs = require('fs');
const Table = require('./lib/Table');
const path = require('path');



const author = process.argv[2];
const files = process.argv.slice(3);
const result = new Table(0);

for (let file of files) {
  const contents = fs.readFileSync(file, { encoding: 'utf-8' });
  const uses = JSON.parse(contents);

  for (let mod in uses) {
    const modStats = uses[mod];
    const usesByAuthor = modStats[author] || 0;
    result.set(path.basename(file, '.json'), mod, usesByAuthor);
  }
}

console.log(result.toCSV());
