#!/usr/bin/node

const pug = require('pug');
const fs = require('fs');
const Table = require('./lib/Table');

const csv = fs.readFileSync(process.argv[2], { encoding: "utf-8" });

const reportData = {
  title: process.argv[2],
  short_title: 'sails',
  table: Table.parse(csv)
}

console.log(pug.renderFile('report.pug', reportData));
