#!/usr/bin/node

const Table = require('./lib/Table');
const fs = require('fs');
const getStdin = require('get-stdin');

getStdin().then(str => {
    console.log(Table.parseJSON(str, 'name').toCSV());
});
