#!/usr/bin/node

// Creates a CSV of the history of API useage of one author.
// Pass the author to extract and a list of useage json files or a dir to extract from

const track = require('./lib/track');



const author = process.argv[2];
let files = process.argv.length == 4 ? process.argv[3] : process.argv.slice(3);
console.log(track.author(author, files).toCSV());
