#!/usr/bin/node

// Creates a CSV of the history of API useage of one module.
// Useage: `./graph_module MODULE USEAGE_JSON...`
// Pass the module to graph and a list of useage json files to extract from

const track = require('./lib/track');



const mod = process.argv[2];
let files = process.argv.length == 4 ? process.argv[3] : process.argv.slice(3);
console.log(track.module(mod, files).toCSV());
